name: Publish Docker image
on:
  - push

jobs:
  publish_image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git clone https://github.com/facebook/bistro.git

      - run: sudo ./bistro/build/fbcode_builder/docker_enable_ipv6.sh

      # Because master is bugged
      - run: cd bistro && git checkout 9b8bad1dd0a9b368e63f6b097b07b5faea9d0c35

      - name: Prepare Dockerfile
        run: |
          cd bistro/build && ./fbcode_builder/make_docker_context.py \
            --make-parallelism=$(nproc) \
            --docker-context-dir=../../ \
            --local-repo-dir="../" \
            --os-image="ubuntu:18.04" \
            --gcc-version=7

      # docs: https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: rectorphp/docker-base-bistro-image-builder/bistro
          tag_with_ref: true
