name: Publish Docker image
on:
  - push

jobs:
  publish_image:
    name: Publish Docker image
    runs-on: ubuntu-18.04
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - run: git clone https://github.com/facebook/bistro.git

      - run: sudo ./bistro/build/fbcode_builder/docker_enable_ipv6.sh

      # Because master is bugged
      - run: cd bistro && git checkout 9b8bad1dd0a9b368e63f6b097b07b5faea9d0c35

      - name: Prepare Dockerfile
        run: |
          cd bistro/build && ./fbcode_builder/make_docker_context.py \
            --make-parallelism=$(nproc) \
            --docker-context-dir=../../ \
            --local-repo-dir="../" \
            --os-image="ubuntu:18.04" \
            --gcc-version=7
          ls -la

      -
          name: Login to GHCR
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      # docs: https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/phpmate/bistro:latest
